replicaCount: 3

image:
  repository: chaitra2711/backend
  tag: latestV1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

config:
  APP_ENV: dev
  APP_PORT: "5000"

secret:
  username: chaitra2711
  password: Selflovechai@123