name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: docker build -t backend:latest ./backend

      - name: Build Frontend Image
        run: docker build -t frontend:latest ./Frontend

      - name: Show Images
        run: docker images
